version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: protocol-bridge-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=protocol-bridge

  # Redis service (for production caching)
  redis:
    image: redis:alpine
    container_name: protocol-bridge-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Keycloak service for SAML/OIDC
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: protocol-bridge-keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

  # Protocol Bridge Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: protocol-bridge-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
      - keycloak
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SERVER_BASE_URL=http://localhost:5000
      - MONGODB_URI=mongodb://mongodb:27017/protocol-bridge
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=your-development-jwt-secret-change-in-production
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=protocol-bridge-client
      - SAML_ENTRY_POINT=http://keycloak:8080/auth/realms/master/protocol/saml
      - SAML_ISSUER=protocol-bridge-saml
      - SAML_CALLBACK_URL=http://localhost:5000/api/auth/saml/callback
      - CORS_ORIGIN=http://localhost:3000
      - SESSION_SECRET=your-development-session-secret-change-in-production
    volumes:
      - ./server:/app
      - /app/node_modules

  # Protocol Bridge Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: protocol-bridge-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:
  redis_data:
  keycloak_data:
